apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uak1p8g7q-go
  janus-idp.io/tekton: uak1p8g7q-go
  backstage.io/kubernetes-id: uak1p8g7q-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uak1p8g7q-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
